---
name: Package mc_rtc
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  pull_request:
    branches:
    - "**"
  push:
    paths-ignore:
    - ".gitlab-ci.yml"
    - ".jrl-ci"
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    - ".pre-commit-config.yaml"
    branches:
    - "**"
    tags:
    - v*
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      deps: '["jrl-umi3218/mc_rtc_ros", "jrl-umi3218/mc_openrtm", "jrl-umi3218/mc_udp", "jrl-umi3218/mc_panda", "jrl-umi3218/mc_state_observation"]'
      with-ros: true
      latest-cmake: true
      matrix: |
          {
            "dist": ["bionic", "focal", "jammy"],
            "arch": ["amd64"],
            "include":
            [
              {"dist": "bionic", "arch": "i386" }
            ]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
